//NEED TO SET THE INCLUDES:
//1.right click on NiosFighter Project
//2.select properties, and go to C/C++ general
//3.Add the Sprite file system
#include "backgroundwithoutbars.h"
#include "blockbar.h"
#include "blocking1.h"
#include "blocking2.h"
#include "filledhealthbar.h"
#include "hit1.h"
#include "hit2.h"
#include "punching1p1.h"
#include "punching1p2.h"
#include "punching1p3.h"
#include "punching1p4.h"
#include "punching2p1.h"
#include "punching2p2.h"
#include "punching2p3.h"
#include "punching2p4.h"
#include "standing1p1.h"
#include "standing1p2.h"
#include "standing1p3.h"
#include "standing1p4.h"
#include "standing1p5.h"
#include "standing1p6.h"
#include "standing1p7.h"
#include "standing2p1.h"
#include "standing2p2.h"
#include "standing2p3.h"
#include "standing2p4.h"
#include "standing2p5.h"
#include "standing2p6.h"
#include "standing2p7.h"
#include "startbackgroundyellow.h"
